name: Create TV Directory and File

on:
  push:
    branches:
      - main
  schedule:
    # 每3分钟运行一次
    - cron: '*/3 * * * *'

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create TV directory
        run: mkdir -p TV

      - name: Create 123.txt file with numbers 1 to 10
        run: |
          echo "Creating 123.txt file with numbers 1 to 10"
          for i in {1..10}; do echo $i; done > TV/123.txt
          ls -la TV
          cat TV/123.txt

      - name: Verify TV directory and 123.txt file
        run: |
          echo "Verifying the TV directory and 123.txt file"
          if [ -d "TV" ]; then echo "TV directory exists"; else echo "TV directory does not exist"; fi
          if [ -f "TV/123.txt" ]; then echo "123.txt file exists"; else echo "123.txt file does not exist"; fi
          cat TV/123.txt
