name: Create Folder and File
 
on:
  push:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Create a folder
      run: mkdir my_folder
 
    - name: Create a file and write to it
      run: |
        echo "123" > my_folder/my_file.txt
