name: Create TV Directory and File

on:
  push:
    branches:
      - main
  schedule:
    # 每3分钟运行一次
    - cron: '*/3 * * * *'

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create TV directory
        run: mkdir -p TV

      - name: Create 123.txt file with numbers 1 to 10
        run: |
          for i in {1..10}; do echo $i; done > TV/123.txt

      - name: Display the contents of 123.txt
        run: cat TV/123.txt
