name: Run Shell Script Example

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run shell script to create folder
      run: ./create_folder.sh
