name: Fetch IPTV Streams

on:
  schedule:
    - cron: '*/3 * * * *'  # 每3分钟执行一次

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
          python -m pip install requests cryptography

      - name: Run Python script to fetch IPTV streams
        run: python fetch_iptv_streams.py > iptv_streams.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: iptv-streams
          path: iptv_streams.txt
