name: Fetch IPTV Streams

on:
  schedule:
    - cron: '*/3 * * * *'  # 每3分钟执行一次

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Bash
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Run Bash script to fetch IPTV streams
        run: |
          bash fetch_iptv_streams.sh > iptv_streams.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: iptv-streams
          path: iptv_streams.txt
