name: Get Workflow Logs

on:
  workflow_run:
    workflows: ["Run Script Every 3 Minutes"]
    types:
      - completed

jobs:
  get_logs:
    runs-on: ubuntu-latest

    steps:
      - name: Get Workflow Run ID
        id: get_workflow_run_id
        run: echo "::set-output name=run_id::${{ github.event.workflow_run.id }}"

      - name: Get Job ID
        id: get_job_id
        run: |
          run_id=${{ steps.get_workflow_run_id.outputs.run_id }}
          job_name="Run PHP script" # 此处填写你想要获取日志的步骤名称
          job_id=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${run_id}/jobs" \
            | jq -r ".jobs[] | select(.name == \"$job_name\") | .id")
          echo "::set-output name=job_id::$job_id"

      - name: Get Job Logs
        id: get_job_logs
        run: |
          run_id=${{ steps.get_workflow_run_id.outputs.run_id }}
          job_id=${{ steps.get_job_id.outputs.job_id }}
          curl \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3.raw" \
            -o logs.txt \
            -L "https://api.github.com/repos/${{ github.repository }}/actions/jobs/${job_id}/logs"
