name: Get Workflow Logs

on:
  workflow_run:
    workflows: ["Run Script Every 3 Minutes"]
    types:
      - completed

jobs:
  get_logs:
    runs-on: ubuntu-latest

    steps:
      - name: Get Workflow Run ID
        id: get_workflow_run_id
        run: echo "::set-output name=run_id::${{ github.event.workflow_run.id }}"

      - name: Get Workflow Logs
        id: get_workflow_logs
        run: |
          run_id=${{ steps.get_workflow_run_id.outputs.run_id }}
          curl \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3.raw" \
            -o logs.txt \
            -L "https://api.github.com/repos/${{ github.repository }}/actions/runs/${run_id}/logs"
