name: PHP Script Execution

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: curl, dom, mbstring, xml
          coverage: none

      # 添加步骤以创建空文件
      - name: Create empty output and error files
        run: |
          touch output.txt
          touch error.txt

      - name: Run PHP script and capture output
        run: |
          php huoqu.php > output.txt 2> error.txt
          cat output.txt || echo "Output file is empty."
          cat error.txt || echo "No error output."

      - name: Upload output and error files
        uses: actions/upload-artifact@v2
        with:
          name: script-output
          path: |
            output.txt
            error.txt
